### ISSUE TITLE
Cluster annotations do not match cluster names

### ISSUE THREAD

**Issue by eam12** [iferres/pagoo#55]
I just discovered this tool and am really enjoying it for processing my output data from Roary. Thank you for creating it!

I'm using `roary_2_pagoo()` to read my Roary output file. However, when I then run `p$clusters` the annotations do not match the cluster names. It seems that the "Annotations" column was somehow scrambled during the conversion to the R6 class object. I can't seem to figure out if there's a pattern to the shifts (e.g. all Annotation rows are shifted down one), but I haven't found anything.

I'm using Pagoo version 0.3.9 with R version 4.1.2. 

 `test <- roary_2_pagoo("test.csv")`

> Reading csv file (roary).
> Processing csv file.
> Loading PgR6M class object.
> Checking class.
> Checking dimnames.
> Creating gid (gene ids).
> Checking provided cluster metadata.
> Creating panmatrix.
> Populating class.
> Done.

`test$clusters`

> DataFrame with 30 rows and 2 columns
>       cluster             Annotation
>      <factor>            <character>
> 1   ccdA      IS200/IS605 family t..
> 2   ccdB        hypothetical protein
> 3   dbpA        hypothetical protein
> 4   faeE       putative protein YjiK
> 5   group_103   hypothetical protein
> ...       ...                    ...
> 26      lpfC'         Antitoxin CcdA
> 27      pemI    hypothetical protein
> 28      pemK    hypothetical protein
> 29      xerD          Antitoxin PemI
> 30      yjiK    hypothetical protein

**Comment by iferres** [comment]
Hi @eam12, thanks for reporting this! 
Could you upload roary's file here ("test.csv") so I can debug it?

**Comment by eam12** [comment]
Thanks so much!

[test.csv](https://github.com/iferres/pagoo/files/7953342/test.csv)

**Comment by iferres** [comment]
I have just pushed changes to fix it. Re-install pagoo from source:
```r
remotes::install_github("iferres/pagoo")
```
Please, let me know if anything. And thanks again for reporting!

**Comment by eam12** [comment]
Looks like its working now. Thanks so much!

**Comment by iferres** [comment]
Great! I will push the latest version to CRAN as soon as possible.
