### ISSUE TITLE
how to add metadata in gene_presence_absence.csv file?

### ISSUE THREAD

**Issue by neelam19051** [iferres/pagoo#62]
As you have mentioned in your paper pca analysis of accessory gene with respect to host in this script which is given below. Please let me know if possible, how to analyze such type of metadata in detail?. I mean i want to know that how did you add metadata in the analysis or in csv file. 
p$gg_pca(color = "Host", size = 4) +
theme_bw(base_size = 15) +
scale_color_brewer(palette = "Set2") https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8487088/pdf/main.pdf!

Thank you !

**Comment by iferres** [comment]
Hi, this is achieved by providing a table with organisms metadata to the pangenome object. It just need a column named "org" with exactly the same organism names as in the object to be able to match the metadata to each organisms.
In the [pagoo webpage](https://iferres.github.io/pagoo/) you have some tutorials, and specifically for this case check out the [Adding Metadata After Object Creation](https://iferres.github.io/pagoo/articles/Input.html#adding-metadata-after-object-creation) section. 
Hope this helps!
